services:
  nginx:
    container_name: dev-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./html:/var/www/html:z
    depends_on:
      - php
  php:
    container_name: dev-php
    build:
      context: ./mysqli_php
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
    # command: 'sh -c "docker-php-ext-install mysqli 
                # && php-fpm --nodaemonize" '
    ports:
        - "9000:9000"

  mysql:
      image: mysql
      container_name: dev-mysql
      restart: always
      env_file:
          - ".env"
      environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
          - "3306:3306"
      volumes:
        - "./mysql:/var/lib/mysql:Z"
  myadmin:
      image: phpmyadmin/phpmyadmin
      container_name: dev-myadmin
      ports:
          - "8080:80"
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=${MYSQL_HOST}
      restart: always
      depends_on:
          - mysql

volumes:
  html:
  conf:
  mysql:

